#!/bin/bash
# Generated by manifest generator
set -x
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/var/log/cloud-init-output.log) 2>&1
apt update
su - root -c "docker run -d -p 80:80 --name miq-test anayyadav/nginx-miq:latest"
set +x